language: java
sudo: false

matrix:
  include:
    - jdk: oraclejdk9
    - before_install: install-jdk10.sh

install:
  cd runner
  javac --release 9 -d ../bin Runner.java
  cd - 

script:
  java -classpath bin Runner

