language: java
sudo: false

matrix:
  include:
    - jdk: oraclejdk9
    - before_install: . ./install-jdk10.sh
    - before_install: . ./install-jdk10.sh && . ./install-jlink-image.sh

before_install:
  - unset _JAVA_OPTIONS

install:
  - cd runner
  - javac --release 9 -d ../bin Runner.java
  - cd - 

script:
  - java -classpath bin Runner

