language: java
sudo: false

matrix:
  include:
    - jdk: oraclejdk9
      env: JDK_VERSION='1.2'
      sudo: true
      services: docker
      before_install:
        - unset _JAVA_OPTIONS && . ./install-jdk2.sh
        - docker run -v ~/jdk:/jdk -e LD_LIBRARY_PATH=jdk/jdk1.2.2/jre/lib/i386/ -d -it i386/ubuntu bash > container_id
        - export DOCKER_CONTAINER_ID=`cat container_id`
    - jdk: oraclejdk9
      env: JDK_VERSION='1.5'
      before_install: unset _JAVA_OPTIONS && . ./install-jdk5.sh
    - jdk: oraclejdk9
      env: JDK_VERSION='1.6'
      before_install: unset _JAVA_OPTIONS && . ./install-jdk6.sh
    - jdk: oraclejdk9
      env: JDK_VERSION='1.7'
      before_install: unset _JAVA_OPTIONS && . ./install-jdk7.sh
    - jdk: oraclejdk9
      env: JDK_VERSION='1.8'
      before_install: unset _JAVA_OPTIONS && . ./install-jdk8.sh
    - jdk: oraclejdk9
      env: JDK_VERSION='9'
    - jdk: oraclejdk9
      env: JDK_VERSION='10'
      before_install: unset _JAVA_OPTIONS && . ./install-jdk.sh
    - jdk: oraclejdk9
      env: JDK_VERSION='10-jlink'
      before_install: unset _JAVA_OPTIONS && . ./install-jdk.sh && . ./install-jlink-image.sh

before_install:
  - unset _JAVA_OPTIONS

install:
  - cd runner
  - javac --release 9 -d ../bin Runner.java
  - cd - 

script:
  - java -classpath bin Runner
